### ISSUE TITLE
php7.4で動作しない

### ISSUE THREAD

**Issue by fuchigam1** [materializing/TextReplace#3]

**Comment by fuchigam1** [comment]
動作はするようなので、何か条件がありそうなため確認中。。。
- phpバージョン
- 一緒に入れているプラグイン
とか。

**Comment by ghost** [comment]
ご報告です。MAMP6.3環境で確認したところ、PHPバージョン7.3.24では、動作問題ありませんでしたが、
7.4.12では、動作しませんでした。
baserCMSバージョンおよび一緒に入れているプラグインの影響ということではなかったようです。

**Comment by fuchigam1** [comment]
@MOMOGUSSAN 詳細ご連絡までいただいて恐縮です。ありがとうございます。
php7.4がNGということでなにかありそうです。見てみます。

**Comment by fuchigam1** [comment]
@MOMOGUSSAN きっかけいただいてありがとうございました。
力技で申し訳ありませんが、php7系でもまず動作するようにいたしました。
本件、クローズいたします。

**Comment by HATTANTOCO** [comment]
@fuchigam1 アカウントを変更した関係で、確認が遅くなりました。ご対応ありがとうございます。
アップデートして利用させていただきます。
